version: '3'
services:
  nodejs: 
    build: 
      context: .
    image: tiotobing/nodejs
    restart: unless-stopped
    container_name: community-solid-server
    environment:
      CSS_ROOT_FILE_PATH: /data
      CSS_BASE_URL: "${PROTOCOL}://${DOMAIN_NAME}/"
      EMAIL_SENDER_NAME: "${EMAIL_SENDER_NAME}"
      EMAIL_HOST: "${EMAIL_HOST}"
      EMAIL_PORT: "${EMAIL_PORT}"
      EMAIL_AUTH_USER: "${EMAIL_AUTH_USER}"
      EMAIL_AUTH_PASS: "${EMAIL_AUTH_PASS}"
    volumes:
      - ${DATA_FOLDER}:/data
    extra_hosts:
      - "${DOMAIN_NAME}:172.17.0.1"
  nginx: 
    build: ./docker/nginx
    image: tiotobing/nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
      - "443:443"
    environment:
      SERVER_NAME: $DOMAIN_NAME
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./docker/certbot/data:/etc/letsencrypt
      - ./docker/certbot/data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - nginx